### ISSUE TITLE
Launch Failure On Mac Ventura

### ISSUE THREAD

**Issue by h3llo-wor1d** [FujiAPI/Fuji#95]
### Please confirm the following

- [X] I am using the latest stable/beta version of Fuji
- [X] I have confirmed that this issue is not caused by a faulty mod
- [X] I have searched and confirmed that this issue is not a duplicate

### What were you doing?

Launch the game on Mac

### Your logs

```shell
System.NotImplementedException: The method or operation is not implemented.
   at MonoMod.Core.Platforms.Systems.MacOSSystem..ctor()
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentSystem()
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent()
   at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock,  init, TParam obj)
   at MonoMod.Core.Platforms.PlatformTriple.get_Current()
   at MonoMod.Core.DetourFactory.CreateDefaultFactory()
   at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location,  init, TParam obj)
   at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory()
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase source, Manipulator manip, DetourConfig config, Boolean applyByDefault)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase source, Manipulator manip, DetourConfig config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase source, Manipulator manip)
   at Celeste64.Mod.Patches.Keyboard.<>c.<Load>b__3_1(MethodInfo m) in /Users/runner/work/Fuji/Fuji/Source/Mod/Patches/Keyboard.cs:line 25
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Celeste64.Mod.Patches.Keyboard.Load() in /Users/runner/work/Fuji/Fuji/Source/Mod/Patches/Keyboard.cs:line 22
   at Celeste64.Mod.Patches.Patches.Load() in /Users/runner/work/Fuji/Fuji/Source/Mod/Patches/Patches.cs:line 7
   at Celeste64.Game.Startup() in /Users/runner/work/Fuji/Fuji/Source/Game.cs:line 211
   at Foster.Framework.App.Run(String applicationName, Int32 width, Int32 height, Boolean fullscreen, Renderers renderer)
   at Foster.Framework.App.Run[T](String applicationName, Int32 width, Int32 height, Boolean fullscreen, Renderers renderer)
   at Celeste64.Launcher.Program.Main(String[] args) in /Users/runner/work/Fuji/Fuji/Celeste64.Launcher/Program.cs:line 52
Game Output:
Celeste 64 v.1.1.1
Fuji: v.0.7.0
Foster: v0.1.18
Platform: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Tue Nov  7 21:42:31 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_ARM64_T8112 (Arm64)
Framework: .NET 8.0.6
SDL: v2.30.0
OpenGL: v4.1 Metal - 83.1, Apple M2
```

**Comment by axiand** [comment]
This is for MonoMod to resolve. I think this is the relevant issue: MonoMod/MonoMod#90

Using the osx_x64 release might work?
